-- Create Databse
CREATE DATABASE customer_analysis	;
-- Active Databse
use customer_analysis;

SELECT * FROM customer_analysis.customer_behviour;
-- --------------------------------------------------------------------------------------------------------------
-- Bussiness Insights:-
-- --------------------------------------------------------------------------------------------------------------

-- ❓ Business Problem :- Company does not know which category contributes most to revenue.
-- 🚀 Impact :- 
			 -- Helps prioritize high-performing categories
			 -- Optimizes inventory planning
			 -- Improves marketing ROI
             
-- 1. Which category generates highest revenue?
SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS 'Highest_revneue'
FROM
    customer_behviour
GROUP BY category
ORDER BY Highest_revneue DESC;



-- 2. Are discounts actually increasing purchase value?
SELECT 
	discount_applied,
	ROUND(SUM(purchase_amount),2) AS total_revenue,
	ROUND(AVG(purchase_amount),2) AS avg_purchase    -- purcahse amount spend by customer per order
FROM customer_behviour
GROUP BY discount_applied;

-- 3. What is the total revenue generated by male and female customer ? 
-- ❓ Business Problem :- Lack of understanding of revenue contribution by gender segments.

-- 🚀 Impact:- 
			-- Helps design targeted marketing campaigns
			-- Improves customer segmentation strategy
			-- Enhances personalization efforts
SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS 'Highest_revneue'
FROM
    customer_behviour
GROUP BY gender
ORDER BY Highest_revneue DESC;

-- 4. Which customer used a discount but still spent more then the average purchase amount ?
--  ❓ Business Problem:- Company cannot identify high-spending customers who are also discount users.
-- 🚀 Impact:- 
			-- Identifies premium discount-sensitive customers
			-- Enables targeted discount campaigns
			 -- Improves customer retention and revenue
select customer_id,
   purchase_amount as "Total_amount"
from customer_behviour
where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount) from customer_behviour)
order by Total_amount desc
limit 10;

-- ------------------------------------------------------------------------------------------------------
-- 5. Which are the top/bottom 5 products with the highest average review rating. 
-- Top 5 Highest review rating
-- ❓ Business Problem :- No visibility into product performance based on customer satisfaction.

-- 🚀 Impact :- 
				-- Promotes high-performing products
				-- Improves low-rated products
				-- Enhances customer experience
select item_purchased,
round(avg(review_rating),1) as "Highest_review_rating"
from customer_behviour
group by item_purchased
order by Highest_review_rating desc
limit 5;

-- Bottom 5 Highest review rating
select item_purchased,
round(avg(review_rating),1) as "Highest_review_rating"
from customer_behviour
group by item_purchased
order by Highest_review_rating asc
limit 5;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 6. Average purchase: Standard vs Express shipping
-- ❓ Business Problem :- Unclear if faster shipping leads to higher spending.
-- 🚀 Impact
			-- Helps optimize shipping pricing strategy
			-- Encourages premium shipping adoption
			-- Increases average order value
SELECT 
    shipping_type,
    COUNT(DISTINCT customer_id) AS 'order_placed',
    ROUND(SUM(purchase_amount), 2) AS 'Revenue',
    ROUND(AVG(purchase_amount), 2) AS 'Avg_purhcase'
FROM
    customer_behviour
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type
ORDER BY Revenue DESC;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
-- ❓ Business Problem :- The effectiveness of subscription programs is unknown.

-- 🚀 Impact
			-- Validates subscription model performance
			-- Improves customer loyalty programs
			-- Increases customer lifetime value (CLV)
SELECT 
    subscription_status,
    COUNT(DISTINCT customer_id) AS 'Customer',
    ROUND(SUM(purchase_amount), 2) AS 'Total_Revenue',
    ROUND(AVG(purchase_amount), 2) AS 'avg_revenue'
FROM
    customer_behviour
GROUP BY 1
ORDER BY Total_Revenue DESC;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 8. Top 5 products with highest discount usage %
-- ❓ Business Problem :- Some products may be overly dependent on discounts.

-- 🚀 Impact:- 
			-- Identifies discount-driven products
			-- Helps optimize pricing strategy
			-- Reduces profit margin loss
SELECT 
	item_purchased,
	COUNT(item_purchased) AS total_number_of_times_sold,
	COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) AS  Number_of_times_sold_when_disocunt_applied,
	COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) *100.0 / COUNT(*) AS discount_percent
FROM customer_behviour
GROUP BY item_purchased
ORDER BY discount_percent DESC
limit 5;

-- SELECT discount_applied,
-- 	COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) AS  Number_of_times_sold_when_disocunt_applied
-- FROM customer_behviour
-- group by discount_applied;

-- SELECT discount_applied,
-- CASE WHEN discount_applied='Yes' THEN 1 END AS  Number_of_times_sold_when_disocunt_applied
-- FROM customer_behviour;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase,and show the count of each segment.
-- ❓ Business Problem :- Lack of customer segmentation leads to generic strategies.
-- 🚀 Impact:- 
			-- Enables personalized marketing
			-- Improves retention strategies
			-- Increases conversion rates

select 
case 
when previous_purchases  = '0' then "New Customer"
when previous_purchases between 1 and 15 then "Returning customer"
else "Loyal Customer"
end as customer_segment,
count(*) as "Total_Customers"
from customer_behviour
group by customer_segment ;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 10. What are the top 3 most purchased products within each category ?

-- ❓ Business Problem:- The company doesn’t know top-performing products within categories.
-- 🚀 Impact
			-- Improves product placement & recommendations
			-- Helps inventory optimization
			-- Increases sales through best-sellers

with cte as(
select category,
item_purchased,
rank() over(partition by category order by count(item_purchased) desc) as rnk
from customer_behviour
group by 1,2
)
select * 
from cte
where rnk <=3;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

-- ❓ Business Problem :- Unclear relationship between loyalty and subscription.
-- 🚀 Impact:- 
			-- Improves subscription targeting
			-- Increases conversion to paid programs
			-- increase customer retention strategy
            
select count(*) as cutomer_count,
subscription_status,
case when previous_purchases > 5 then "Repeat Buyers"
 else "Noraml Buyers"
end as Customer_type
from customer_behviour
group by 2,3;

-- --------------------------------------------------------------------------------------------------------------------------------
-- 12. What is the revenue contribution of each age group ? 

-- ❓ Business Problem:- No visibility into which age group contributes most to revenue.
-- 🚀 Impact:-
			-- Enables age-based targeting
			-- Enhances marketing efficiency
select CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,	
round(sum(purchase_amount),2) as "Total_revenue"
from customer_behviour
group by age_group
order by Total_revenue desc;

-- -----------------------------------------------------------------------------------------------------------------------------
-- Average order Value (AOV)
SELECT AVG(purchase_amount) as aov
from customer_behviour;


-- --------------------------------------------------------------------------------------------------------------------------------
-- Which purchase frequency generates maximum revenue?
select round(sum(purchase_amount),2) as  maximum_revenue,
frequency_of_purchases
from customer_behviour
group by frequency_of_purchases 
order by maximum_revenue desc;

-- -------------------------------------------------------------------------------------------------------------------------------
-- Do weekly customers spend more?
SELECT 
    frequency_of_purchases,
    ROUND(AVG(purchase_amount),2) AS avg_spending,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer_behviour
GROUP BY frequency_of_purchases
ORDER BY avg_spending DESC;
-- Yes, weekly customers spend more on average. These are high-value customers and 
-- should be targeted with loyalty programs, memberships, or exclusive discounts.

-- --------------------------------------------------------------------------------------------------------------------------
SELECT 
    frequency_of_purchases,
    subscription_status,
    COUNT(*) AS total_customers
FROM customer_behviour
GROUP BY frequency_of_purchases, subscription_status
ORDER BY frequency_of_purchases;


-- -----------------------------------------------------------------------------------------------------------------------------
-- calculating the subscription rate for each purchase frequency.
SELECT 
    frequency_of_purchases,
    ROUND(
        100.0 * SUM(
            CASE 
                WHEN subscription_status = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*), 2
    ) AS subscription_percentage
FROM customer_behviour
GROUP BY frequency_of_purchases
ORDER BY subscription_percentage DESC;



















































